---
component: 'test'
deployment_identifier: "%{hiera('deployment_identifier')}"

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

organization_id: "602e67f467852d083d43a50f"

existing_teams:
  - name: "support"
    usernames:
      - "toby+user1@go-atomic.io"
    role_names:
      - "GROUP_DATA_ACCESS_READ_ONLY"
  - name: "billing"
    usernames:
      - "toby+user2@go-atomic.io"
    role_names:
      - "GROUP_READ_ONLY"

dedicated_teams:
  - name_suffix: "developers"
    usernames:
      - "toby+user1@go-atomic.io"
      - "toby+user2@go-atomic.io"
    role_names:
      - "GROUP_DATA_ACCESS_ADMIN"
      - "GROUP_CLUSTER_MANAGER"
  - name_suffix: "admins"
    usernames:
      - "toby+user3@go-atomic.io"
    role_names:
      - "GROUP_OWNER"

ip_access_list:
  - type: "cidr-block"
    value: "10.0.0.0/8"
    comment: "Private network 1"
  - type: "cidr-block"
    value: "192.168.0.0/16"
    comment: "Private network 2"
  - type: "ip-address"
    value: "1.1.1.1"
    comment: "Public IP 1"
  - type: "ip-address"
    value: "2.2.2.2"
    comment: "Public IP 2"
