---
component: 'test'
deployment_identifier: "%{hiera('seed')}"

organization_id: "602e67f467852d083d43a50f"

existing_teams:
  - name: "%{hiera('component')}-%{hiera('deployment_identifier')}-support"
    usernames: ["toby+user1@go-atomic.io"]
  - name: "%{hiera('component')}-%{hiera('deployment_identifier')}-billing"
    usernames: ["toby+user2@go-atomic.io"]
